services:
  mysql:
    image: mysql:8
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: <root-pwd>
      MYSQL_USER: mysql_user
      MYSQL_DB: unselected_inventory_dashboard
      MYSQL_PASSWORD: <user-pwd>
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: